version: "3"
services:
  db:
    environment:
      - TZ=Asia/Bangkok
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=oasiptt2
    image: mysql:8
    ports:
      - '3306:3306'
    volumes:
      - ./database/script:/docker-entrypoint-initdb.d/

  spring:
    build: ./oasip-service
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.driver-class-name":"com.mysql.cj.jdbc.Driver",
        "spring.datasource.password":"oasiptt2",
        "spring.datasource.username":"test221",
        "spring.datasource.url":"jdbc:mysql://db:3306/oasip",
        "spring.jpa.hibernate.ddl-auto":"none",
        "spring.jpa.hibernate.naming.physical-strategy":"org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
      }'

  
  nginx:
    build: 
      context: "./oasip-vue"
      args:
        - VITE_API_URL=http://ip21tt2.sit.kmutt.ac.th:8080/api
    ports:
      - "80:80"
    depends_on:
      - spring
